[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nmine"
version = "3.2.0"
authors = [
  { name="Steve Benson", email="steve@xelphene.net" },
]
description = "Combines nmap output and DNS data to produce HTTP[S] URLs of interest."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
	"ipcidrtree>=1.3.0"
]

[project.scripts]
nmine="nmine:main.main"

[project.urls]
"Homepage" = "https://github.com/xelphene/nmine"
"Bug Tracker" = "https://github.com/xelphene/nmine/issues"
